part of 'app_pages.dart';

abstract class Routes {
  Routes._();
  static const SPLASH = _Paths.SPLASH;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const LOGIN = _Paths.LOGIN;
  static const MAIN = _Paths.MAIN;
  static const HOME = _Paths.HOME;
  static const PROFILE = _Paths.PROFILE;
  static const ATTENDANCE = _Paths.ATTENDANCE;
  static const PAYSLIP = _Paths.PAYSLIP;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const LEAVE = _Paths.LEAVE;
  static const OVERTIME = _Paths.OVERTIME;
  static const PERMISSION = _Paths.PERMISSION;
  static const WFH = _Paths.WFH;
  static const REIMBURSEMENT = _Paths.REIMBURSEMENT;
  static const KASBON = _Paths.KASBON;
  static const KASBON_DETAIL = _Paths.KASBON_DETAIL;
  static const SETTLEMENT = _Paths.SETTLEMENT;
  static const SETTLEMENT_DETAIL = _Paths.SETTLEMENT_DETAIL;
  static const ANNOUNCEMENT = _Paths.ANNOUNCEMENT;
  static const DOKUMEN = _Paths.DOKUMEN;
  static const VISITING = _Paths.VISITING;
  static const VISITING_REPORT = _Paths.VISITING_REPORT;
  static const SHIFT_SWAP = _Paths.SHIFT_SWAP;
  static const FACE_ENROLL = _Paths.FACE_ENROLL;
  static const FACE_VERIFY = _Paths.FACE_VERIFY;
  static const MSS = _Paths.MSS;
  static const ATTENDANCE_CORRECTION = _Paths.ATTENDANCE_CORRECTION;
  static const SCHEDULE = _Paths.SCHEDULE;
  static const MSS_MEMBER = _Paths.MSS_MEMBER;
  static const MSS_RECAP = _Paths.MSS_RECAP;
  static const DASHBOARD = _Paths.DASHBOARD;
}

abstract class _Paths {
  _Paths._();
  static const SPLASH = '/splash';
  static const ONBOARDING = '/onboarding';
  static const LOGIN = '/login';
  static const MAIN = '/main';
  static const HOME = '/home';
  static const PROFILE = '/profile';
  static const ATTENDANCE = '/attendance';
  static const PAYSLIP = '/payslip';
  static const NOTIFICATION = '/notification';
  static const LEAVE = '/leave';
  static const OVERTIME = '/overtime';
  static const PERMISSION = '/permission';
  static const WFH = '/wfh';
  static const REIMBURSEMENT = '/reimbursement';
  static const KASBON = '/kasbon';
  static const KASBON_DETAIL = '/kasbon/detail';
  static const SETTLEMENT = '/settlement';
  static const SETTLEMENT_DETAIL = '/settlement/detail';
  static const ANNOUNCEMENT = '/announcement';
  static const DOKUMEN = '/dokumen';
  static const VISITING = '/visiting';
  static const VISITING_REPORT = '/visiting/report';
  static const SHIFT_SWAP = '/shift-swap';
  static const FACE_ENROLL = '/face-enroll';
  static const FACE_VERIFY = '/face-verify';
  static const MSS = '/mss';
  static const ATTENDANCE_CORRECTION = '/attendance-correction';
  static const SCHEDULE = '/schedule';
  static const MSS_MEMBER = '/mss-member';
  static const MSS_RECAP = '/mss-recap';
  static const DASHBOARD = '/dashboard';
}
